"""Initial schema.

Revision ID: 758ae71ff489
Revises:
Create Date: 2026-04-19 22:27:19.862007
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "758ae71ff489"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "satellites",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("norad_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_satellites_norad_id"), "satellites", ["norad_id"], unique=True)
    op.create_table(
        "tle_records",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("satellite_id", sa.Integer(), nullable=False),
        sa.Column("tle_line1", sa.String(length=69), nullable=False),
        sa.Column("tle_line2", sa.String(length=69), nullable=False),
        sa.Column("epoch", sa.DateTime(timezone=True), nullable=False),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["satellite_id"], ["satellites.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("satellite_id", "epoch", name="uq_tle_records_satellite_epoch"),
    )
    op.create_index(op.f("ix_tle_records_epoch"), "tle_records", ["epoch"], unique=False)
    op.create_index(
        op.f("ix_tle_records_satellite_id"), "tle_records", ["satellite_id"], unique=False
    )
    op.create_table(
        "processed_tle",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("tle_record_id", sa.Integer(), nullable=False),
        sa.Column("period_minutes", sa.Float(), nullable=False),
        sa.Column("apogee_km", sa.Float(), nullable=False),
        sa.Column("perigee_km", sa.Float(), nullable=False),
        sa.Column("inclination_deg", sa.Float(), nullable=False),
        sa.Column("eccentricity", sa.Float(), nullable=False),
        sa.Column("mean_motion_rev_per_day", sa.Float(), nullable=False),
        sa.Column("orbit_type", sa.String(length=10), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["tle_record_id"], ["tle_records.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tle_record_id", name="uq_processed_tle_tle_record_id"),
    )
    op.create_index(
        op.f("ix_processed_tle_tle_record_id"), "processed_tle", ["tle_record_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_processed_tle_tle_record_id"), table_name="processed_tle")
    op.drop_table("processed_tle")
    op.drop_index(op.f("ix_tle_records_satellite_id"), table_name="tle_records")
    op.drop_index(op.f("ix_tle_records_epoch"), table_name="tle_records")
    op.drop_table("tle_records")
    op.drop_index(op.f("ix_satellites_norad_id"), table_name="satellites")
    op.drop_table("satellites")
    # ### end Alembic commands ###
